spring:
  security:
    oauth2:
      client:
        registration:
          internet-forum:
            client-id: "internet-forum"
            client-secret: "internet-forum-password"
            client-name: "Internet forum"
            provider: "spring"
            scope: "openid"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          spring:
            issuer-uri: "http://localhost:9090"
  threads:
    virtual:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/browser

logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
